# Generated by Django 5.2.8 on 2025-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('EDITOR', 'Editor'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
