# Generated by Django 5.2.8 on 2025-11-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('editor', 'Editor'), ('patient', 'Patient')], help_text='کاربر چه نقشی دارد (Doctor / Editor / Patient).', max_length=20, null=True),
        ),
    ]
