# Generated by Django 5.2.8 on 2025-11-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('title', 'created_at')},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_published',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_at',
        ),
    ]
